spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 21889198455-iihho96itv59us332vs51bu6s2bf5pqk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: Bmu8Ll1Svdml8WMPta9u
            client-secret: pTMHYhdEnN
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: 'https://nid.naver.com/oauth2.0/authorize'
            token-uri: 'https://nid.naver.com/oauth2.0/token'
            user-info-uri: 'https://openapi.naver.com/v1/nid/me'
            user-name-attribute: response

